export const CATEGORIAS = [
  "maquinaria",
  "semillas",
  "cosechas",
  "servicios",
  "fertilizantes",
  "plagas",
  "riego",
  "alimentos",
  "herramientas",
  "insumos",
  "transporte",
  "animales",
  "tierras",
  "refacciones",
  "tecnología",
  "consultoría agrícola",
  "energía solar",
  "productos orgánicos",
  "invernaderos",
  "agroinsumos",
  "forrajes",
];

export const CATEGORIAS_CON_EMOJI = [
  "Maquinaria 🚜",
  "Semillas 🌱",
  "Cosechas 🥕",
  "Servicios 🧰",
  "Fertilizantes 💧",
  "Control de Plagas 🐛",
  "Sistemas de Riego 💦",
  "Alimentos 🍎",
  "Herramientas 🔧",
  "Insumos 📦",
  "Transporte 🚚",
  "Ganado y Animales 🐄",
  "Tierras y Terrenos 🌾",
  "Refacciones ⚙️",
  "Tecnología Agrícola 💻",
  "Consultoría Agrícola 🧑‍🌾",
  "Energía Solar ☀️",
  "Productos Orgánicos 🍃",
  "Invernaderos 🏭",
  "Agroinsumos 🧪",
  "Forrajes y Pastos 🌿",
];
